import { useState } from 'react';
import Head from 'next/head';
import { makeStyles, Grid, TextField } from '@material-ui/core';
import CoinsTable from '../components/CoinsTable';

const useStyles = makeStyles({
  container: { margin: '2em 0' },
  col: { marginBottom: '2em' }
});

export default function Home({ coinsArr }) {
  const classes = useStyles();
  const [crypto, setCrypto] = useState('');

  const handleChange = e => {
    setCrypto(e.target.value);
  };

  return (
    <div>
      <Head>
        <title>Crypto Tracker</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Grid
        container
        className={classes.container}
        direction='column'
        alignItems='center'
      >
        <Grid item className={classes.col}>
          Header
        </Grid>
        <Grid item className={classes.col}>
          <TextField
            label='Search'
            value={crypto}
            onChange={handleChange}
            variant='outlined'
          />
        </Grid>
        <Grid item>
          <CoinsTable coinsArr={coinsArr} />
        </Grid>
      </Grid>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch(
    'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&per_page=250'
  );

  let coinsArr = await res.json();

  return {
    props: { coinsArr }
  };
}
